### ISSUE TITLE
Add React Hooks Plugin to ensure React Hook Rules

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/eslint-config-terra#32]
# Issue Description
Add [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks) plugin to enforce [React Hook Rules](https://reactjs.org/docs/hooks-rules.html).

## Issue Type

- [x] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by ryanthemanuel** [comment]
This was already added: https://github.com/cerner/eslint-config-terra/blob/master/eslint.config.js#L33
