### ISSUE TITLE
Need to downgrade the eslint-plugin-react version to 7.14.3 

### ISSUE THREAD

**Issue by ShettyAkarsh** [cerner/eslint-config-terra#38]
# Issue Description
Will have to downgrade the version of eslint-plugin-react to 7.14.3 temporarily as eslint script scan is giving the following error with the new 7.15.0 version of eslint-plugin-react. 

![image](https://user-images.githubusercontent.com/45097016/65957205-e10dfc80-e469-11e9-8eea-9106777b3305.png)

so there is already an issue logged https://github.com/yannickcr/eslint-plugin-react/issues/2423 to eslint-config-terra to fix this.

## @ Mentions
@bjankord , @ryanthemanuel

**Comment by bjankord** [comment]
Talked in scrum, planning to pin the dep to 7.14.3 until a fix is landed upstream. We'll cut a release once we pin the version down.
