### ISSUE TITLE
Update to eslint v5

### ISSUE THREAD

**Issue by bjankord** [cerner/eslint-config-terra#6]
# Issue Description
eslint v5 has been released: https://eslint.org/blog/2018/06/eslint-v5.0.0-released
We should update our peerDep to use v5 and associated dependencies. We'll likely need to wait on [our dependencies](https://github.com/cerner/eslint-config-terra/blob/master/package.json#L32-L36) to release compat versions with v5.

With this we need to check and see if there are eslint v5 compatible releases for the following:

- [ ] "eslint-config-airbnb" (waiting on release, v17 has been released, however I'm not sure if this is compat with eslint 5 - [more info here](https://github.com/airbnb/javascript/issues/1834))
- [x] "eslint-plugin-compat" ([Issue logged](https://github.com/amilajack/eslint-plugin-compat/issues/120))
- [x] "eslint-plugin-import" (eslint v5 support added in v2.13.0)
- [x] "eslint-plugin-jsx-a11y"  (eslint v5 support set to be added in v6.1.0)
- [x] "eslint-plugin-react" (eslint v5 support added in v7.10.0)

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Config uses eslint v5 and related compatible plugins

**Comment by teriu** [comment]
Support for ESLint v5 just dropped in `eslint-plugin-jsx-a11y` (6.1.0 is out)

**Comment by emilyrohrbough** [comment]
Thanks @teriu!

**Comment by noahbenham** [comment]
Thank you for keeping the ecosystem current. Minor aside, [I've added Cerner](https://github.com/airbnb/javascript/pull/1849) to Airbnb's In The Wild.

**Comment by dv297** [comment]
Looks like the issue linked for eslint-config-airbnb was closed so probably good to go. Also checked the package.json of eslint-config-airbnb, lists || ^5.3.0

https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v17.1.0/packages/eslint-config-airbnb/package.json#L76

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/eslint-config-terra/pull/10 
Forgot to close this via the PR.
