### ISSUE TITLE
Update eslint globals

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/eslint-config-terra#8]
# Issue Description
In a PR from another team consuming terra-toolkit, they added the following to their eslint config... It would make sense for use to add it too so we can remove the following line we add to each test file 

// eslint.config.js
```
"globals": {
  // JEST GLOBALS
  "shallow": true,
  "render": true,
  "mount": true,
  // WDIO GLOBALS
  "Terra": true,
  "before": true,
  "browser": true  
}
```
what we add to tests
```
/* global browser, Terra */
```

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Write tests without writing out the used globals.

## Current Behavior
Must add globals to each test file for eslint

**Comment by dv297** [comment]
Handled with #11
